<a href="https://colab.research.google.com/github/RegisKonan/FinalProject/blob/main/regis_konan_Pytorch_tutorial_part1_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## what is Pytorch

![picture](https://cdn.analyticsvidhya.com/wp-content/uploads/2019/09/pytorch.png)

PyTorch is a Python-based library used to build neural networks.

It provides classes that allow us to easily develop a suite of deep learning models.

It gives maximum flexibility and speed.

## Install pytorch

In [1]:
# !conda install pytorch torchvision -c pytorch
# # or with GPU
# ! conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

#https://pytorch.org/

###Let's import pytorch and check that it's well installed

In [3]:
import torch
print(torch.__version__)

1.13.1+cu116


## Tensors

At its core, PyTorch is a library for processing tensors. Tensors are multidimensional arrays. And PyTorch tensors are similar to NumPy’s n-dimensional arrays. We can use these tensors on a GPU as well (this is not the case with NumPy arrays). This is a major advantage of using tensors. A tensor can be a number, vector, matrix, or any n-dimensional array

PyTorch supports multiple types of tensors, including:

1. FloatTensor: 32-bit float
2. DoubleTensor: 64-bit float
3. HalfTensor: 16-bit float
4. IntTensor: 32-bit int
5. LongTensor: 64-bit int








Let's create a tensor with a single number.

In [4]:
# Number
t1 = torch.tensor(4.)
print(t1.dtype)
print(t1)
print(t1.shape)

torch.float32
tensor(4.)
torch.Size([])


In [5]:
# 1d tensor(vector)
t2 = torch.tensor([1., 2, 3, 4])
print(t2)
print(t2.shape)

tensor([1., 2., 3., 4.])
torch.Size([4])


In [6]:
# 2d tensor or matrix

# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])

print(t3)
print(t3.shape)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
torch.Size([3, 2])


In [7]:
#3d tensor
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
print(t4)
print(t4.shape)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])
torch.Size([2, 2, 3])


## Mathematical operations on tensors

In [ ]:
a =  torch.tensor([1., 2, 3, 4])
b =  torch.tensor([5., 6, 7, 8])

print("===========sum of a and b=============")

print(a + b)
print()
print("===========substracting a from b======")

print(b - a)
print()

print("===========multiplying a and b=========")

print(a * b)
print()
print("===========dividing b per a=============")

print(b/a)

===========sum of a and b=============
tensor([ 6.,  8., 10., 12.])

===========substracting a from b======
tensor([4., 4., 4., 4.])

===========multiplying a and b=========
tensor([ 5., 12., 21., 32.])

===========dividing b per a=============
tensor([5.0000, 3.0000, 2.3333, 2.0000])


## Matrix Initialization

### Create  a matrix of shape 3*3 having all zeros

In [11]:
torch.zeros((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Create  a matrix of shape 3*3 having all ones

In [12]:
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## create  a 3x3 matrix randomly filled

In [15]:
# setting the random seed for pytorch
#torch.set_printoptions(precision=2)
torch.manual_seed(42)
# matrix of random numbers
## torch.randn returns a tensor filled with random numbers from a normal distribution with mean `0` and variance `1`
torch.randn(3,3)


tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [16]:
# torch.randint returns a tensor filled with random integers generated uniformly
torch.randint(0,10,(3,3))

tensor([[9, 6, 3],
        [1, 9, 3],
        [1, 9, 7]])

In [17]:
## torch.rand returns a tensor filled with random numbers from a uniform distribution on the interval `[0, 1)`
torch.rand(3,3)


tensor([[0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040]])

## Torch tensors and numpy conversion

In [63]:
## Tensor to numpy array
#torch.set_printoptions(precision=2)
a = torch.rand(3,3)
print(a)
## convert a into numpy array b
b=a.numpy()
## update the tensor a by adding a value to it
print(b)
##print b
a+=2
print(b)

tensor([[0.25, 0.48, 0.78],
        [0.37, 0.21, 0.33],
        [0.13, 0.68, 0.89]])
[[0.24693054 0.47612214 0.77918065]
 [0.3722331  0.21471256 0.32877856]
 [0.12646258 0.67831624 0.8870201 ]]
[[2.2469306 2.4761221 2.7791805]
 [2.3722332 2.2147126 2.3287785]
 [2.1264625 2.678316  2.88702  ]]


In [34]:
## Numpy array to tensor
import numpy as np
a = np.random.rand(3,3)
print(a)
## convert array a into tensor b
#b=torch.from_numpy(a)
b=torch.from_numpy(a).clone()
print(b)
a+=2
print(b)

[[0.11170064 0.75146991 0.57883692]
 [0.37278833 0.65331156 0.91828078]
 [0.13981351 0.871125   0.14469094]]
tensor([[0.1117, 0.7515, 0.5788],
        [0.3728, 0.6533, 0.9183],
        [0.1398, 0.8711, 0.1447]], dtype=torch.float64)
tensor([[0.1117, 0.7515, 0.5788],
        [0.3728, 0.6533, 0.9183],
        [0.1398, 0.8711, 0.1447]], dtype=torch.float64)


## Matrix operations

In [36]:
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)
print(a)
print(b)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])
tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]])


For addition, substraction and division we can either use torch.add, torch.sub, torch.div or +,  - and /

In [30]:
## compute sum of a and b
a+b

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])

In [38]:
torch.add(a,b)
torch.add(a,torch.add(b,b)) ### add multi numbers

tensor([[ 0.8714,  1.1986,  1.8532],
        [ 2.4509, -4.5025, -2.1642],
        [ 4.1241,  2.0063,  2.0960]])

In [39]:
## compute a -b
print(a-b)

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])


In [40]:
torch.sub(a,b)

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])

In [29]:
##compute a / b

In [41]:
print(a/b)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


In [42]:
torch.div(a,b)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])

In [46]:
torch.sum(b,dim=0)

tensor([2.3356, 0.1672, 0.6376])

## Multiplication

### Elementwise multiplication

In [ ]:
## a * b

In [43]:
a*b

tensor([[ 0.0900,  0.0689,  0.1898],
        [ 0.2557,  1.8974,  0.1843],
        [ 2.1154, -0.8435,  0.3773]])

### matrix multiplication

In [47]:
##using torch.mm
torch.mm(a,b)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [48]:
##using torch.matmul
torch.matmul(a,b)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [49]:
##using @
a@b

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

## Reshape, Transpose and concatenate tensors

In [ ]:
torch.manual_seed(42)
a = torch.randn(3,4)
print(a.shape)
b = a.reshape(-1, 1)
print(b.shape)
c = a.reshape(6,2)
print(c.shape)

torch.Size([3, 4])
torch.Size([12, 1])
torch.Size([6, 2])


In [52]:
a = torch.randn(3,4)
c = a.reshape(6,2)
c

tensor([[-0.7409,  0.3618],
        [ 1.9199, -0.2254],
        [-0.3417,  0.3040],
        [-0.6890, -1.1267],
        [-0.2858, -1.0935],
        [ 1.1351,  0.7592]])

In [53]:
#transpose
a_t = torch.t(a)
print(a_t.shape)

torch.Size([4, 3])


In [54]:
#transpose
print(a.T.shape)

torch.Size([4, 3])


In [55]:
## Concatenate
b = torch.randn(1, 4)
print(b.shape)
concat = torch.cat((a, b), dim=0)
print(concat.shape)

torch.Size([1, 4])
torch.Size([4, 4])


In [56]:
flat_vect = a.flatten()
print(flat_vect)
flat_vect.shape

tensor([-0.7409,  0.3618,  1.9199, -0.2254, -0.3417,  0.3040, -0.6890, -1.1267,
        -0.2858, -1.0935,  1.1351,  0.7592])


torch.Size([12])

## Extra reading

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html
